### ISSUE TITLE
Use a cross platform build system

### ISSUE THREAD

**Issue by mmmaisel** [disks86/VK9#29]
Currently, the VK9 library can be only build with Visual Studio even though the main use case is Linux with Wine.

To support native Linux builds as well as Visual Studio a cross platform build system like CMake or Meson (used by DXVK as well) should be used. With such a tool it would also be possible to automatically compile all GLSL shaders to SPIR-V.

If there is interest in porting the build system I can work on it.

This issue is related to issues #27 and #28.

**Comment by disks86** [comment]
I'd say it's a use case but there are plenty of other uses like quick ports or working around broken d3d9 support in windows drivers. I think VS has experimental support for CMake but it still wouldn't be cross platform because it would be using MSVC not gcc.

**Comment by Kerrung** [comment]
https://github.com/doitsujin/dxvk/blob/master/README.md
Maybe you should use a similar build system such as DXVK uses?

**Comment by Valmar33** [comment]
DXVK's build system allows it to be built and run on Windows natively, as well as on Linux with mingw GCC.

**Comment by mmmaisel** [comment]
Solving this issue would also fix #14.

**Comment by mmmaisel** [comment]
I uploaded a first version which uses Meson [here](https://github.com/mmmaisel/VK9). It compiles fine with MinGW on Linux but I'm unable to get Meson itself working on my old 32bit Windows 7 installation.

Can anybody with a working Windows Meson installation please test if generating Visual Studio projects works as well?

**Comment by Valmar33** [comment]
@mmmaisel What errors is Meson giving you on Windows, out of curiousity?

I'll try out Meson on Windows in a VM soon.

**Comment by Valmar33** [comment]
@mmmaisel Also, how are you building it? Plain Meson doesn't work, which be frustrating for beginners. Try offering a build script like DXVK does, to make it easier for others as well.

**Comment by mmmaisel** [comment]
I added build scripts and build instructions to my meson branch and improved the meson project files. 
The built dll should now work with Wine.

@Valmar33 I get the following error on my Windows box. This happens for all meson projects so it is related to my installation.

```
Run Visual Studio 2017 Developer Command Prompt:
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.6.4
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
meson ./build.vs --backend=vs2017

The Meson build system
Version: 0.45.1
Source dir: C:\Projects\VK9
Build dir: C:\Projects\VK9\build.vs
Build type: native build
Project name: vk9
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python\lib\threading.py", line 916, in _bootstrap_inner
  File "C:\Python\lib\threading.py", line 864, in run
  File "C:\Python\lib\subprocess.py", line 1063, in _readerthread
  File "C:\Python\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 512: char
acter maps to <undefined>

Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Python\lib\threading.py", line 916, in _bootstrap_inner
  File "C:\Python\lib\threading.py", line 864, in run
  File "C:\Python\lib\subprocess.py", line 1063, in _readerthread
  File "C:\Python\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 62: chara
cter maps to <undefined>

Traceback (most recent call last):
  File "mesonbuild\mesonmain.py", line 361, in run
  File "mesonbuild\mesonmain.py", line 150, in generate
  File "mesonbuild\mesonmain.py", line 189, in _generate
  File "mesonbuild\interpreter.py", line 1444, in __init__
  File "mesonbuild\interpreterbase.py", line 159, in parse_project
  File "mesonbuild\interpreterbase.py", line 195, in evaluate_codeblock
  File "mesonbuild\interpreterbase.py", line 189, in evaluate_codeblock
  File "mesonbuild\interpreterbase.py", line 200, in evaluate_statement
  File "mesonbuild\interpreterbase.py", line 456, in function_call
  File "mesonbuild\interpreterbase.py", line 55, in wrapped
  File "mesonbuild\interpreterbase.py", line 79, in wrapped
  File "mesonbuild\interpreter.py", line 1947, in func_project
  File "mesonbuild\interpreter.py", line 2078, in add_languages
  File "mesonbuild\interpreter.py", line 2001, in detect_compilers
  File "mesonbuild\environment.py", line 543, in detect_c_compiler
  File "mesonbuild\environment.py", line 497, in _detect_c_or_cpp_compiler
  File "mesonbuild\mesonlib.py", line 722, in Popen_safe
  File "C:\Python\lib\subprocess.py", line 843, in communicate
  File "C:\Python\lib\subprocess.py", line 1113, in _communicate
IndexError: list index out of range
```

**Comment by Valmar33** [comment]
@mmmaisel Thanks, will test.

Try the Ninja backend on Windows. It is apparently more feature-complete and stable, according to the Meson documentation:

http://mesonbuild.com/Using-with-Visual-Studio.html

"If you wish to use the Ninja backend instead of vs2015, pass --backend ninja. At the time of writing the Ninja backend is more mature than the VS backend so you might want to use it for serious work."

**Comment by Valmar33** [comment]
Also, it complains:

"Cross dependency 'vulkan-1' not found"

Should test the workflow on Windows, also, to streamline it as much as possible for @disks86

**Comment by Valmar33** [comment]
Also, it complains that it cannot find spirv or eigen, despite me having mingw-w64-eigen installed and spirv installed natively.

**Comment by Valmar33** [comment]
Ah, just saw your README.md.

**Comment by Valmar33** [comment]
@mmmaisel Ninja does work with Visual Studio. They mention it here:

https://ninja-build.org/manual.html#_deps

They can build using the Visual Studio compiler on Windows, so it doesn't depend on GCC or Clang.

**Comment by sykhro** [comment]
The easiest way to use meson on Windows is via msys2 (uses pkg-config for dependencies, basically identical to linux). If you don't want to go down that route, just make sure all your deps are in your %PATH%.

If you want to use msvc, you can pass --backend vs2015 (or 2017) to the meson builddir command. This will generate a visual studio solution that can be opened directly for building. It does have a couple bugs still (like some cxx flags not being set properly), which is why it would be better to use Ninja.

Either way, you need to run VS' vcvarsall.bat to properly init the environment.

**Comment by mmmaisel** [comment]
@Valmar33 Thanks for the infop that ninja build is possible on Windows. However this does not fix my meson error which seems to be related to calling the MSVC compiler "cl".

**Comment by disks86** [comment]
This is resolved now that mmmaisel's pull request has been merged.
